Repository LACMTA/marketing-docs, pull requests merged in 2021-11, with the labels that each got.

#38 Added information on automation
  .github/workflows/merge.yml
  docs/_Processes/realignment/media/chart.png
  docs/_Projects/mybus/MyBus.md
  docs/_Resources/automation/automation.md
  docs/_Resources/automation/github-auto-labeler.md
  docs/_Resources/automation/repository-labels.md
  docs/_Resources/automation/standard-repository-labels.md
  docs/working_groups/index.md
Labels: Priority: Medium

#44 Create readme.md
  docs/_Processes/WordPress/readme.md
Labels: 0-Priority: Low

#65 Added documentation on the My Canceled Bus tool
  docs/_Getting-Started/contacts.md
  docs/_Projects/my-canceled-bus/readme.md
Labels: 0-Priority: Medium, Type: Documentation
